version: '3.8'

services:
   webserv:
     build: .
     container_name: webserv
     volumes:
       - "/Users/donghank/webserv:/mnt/project"  # mount the host directory to the container (you can replace with your path)
     ports: # the ports to expose
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
     tty: true
